config/routes.rb
Cordel::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "sign_in",  :to => "devise/sessions#new"
    get "sign_up",  :to => "devise/registrations#new"
    get "sign_out", :to => "devise/sessions#destroy"  
  end

  devise_scope :user do
    get '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'
    get '/users/auth/facebook/callback' => 'users/omniauth_callbacks#passthru'
  end

  resources :books do
    collection do
      get :search
    end
  end
  
  resources :shelves do
    get :put_the_book_on_the_shelf, :path_prefix => '/shelves/:id', :requirements => { :extra => :book_id }, :on => :member
  end
  
  resources :authors
  
  root :to => "home#index"
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  
#  attr_accessible :thumb_image_path
  
  belongs_to :user
  validates_presence_of :user
  
  belongs_to :author
  accepts_nested_attributes_for :author
  validates_presence_of :author

  has_many :pages, :dependent => :destroy  
  
  has_attached_file :file
  validates_attachment_presence :file
  validates_attachment_size :file, :less_than => 20.megabytes
  validates_attachment_content_type :file, :content_type => ['application/pdf']
  
  attr_accessor :author_highlighted, :pages_content_highlighted, :title_highlighted, :publisher_highlighted
  searchable do
    text :author, :stored => true do
      author.try(:name)
    end
    text :title, :stored => true
    text :edition
    text :publisher, :stored => true
    text :year
    text :pages_content, :stored => true do
      pages.map do |page|
        page.content
      end
    end
    integer :user_id
  end
  
  @queue = :file_serve
  def process(book_id)
    book = Book.find(book_id)
    
    #url = Rails.root.to_s + "/public" + Book.find(66).file.url(:original, :timestamp => false)
    url = Rails.root.to_s + "/public" + "/system/files/66/original/crafting-rails-applications_p1_0.pdf"
    PDF::Reader.open(url) do |reader|
      puts reader.info.inspect
      
      info = reader.info
      puts "Title => " + info[:Title]
      puts "Author => " + info[:Author]
      
    end

    url = Rails.root.to_s + "/public" + book.file.url(:original, :timestamp => false)
  	receiver = PageTextReceiver.new
    pdf = PDF::Reader.file(url, receiver)
    page_number = 0
    book.pages = []
    receiver.content.each{|page|      
      page_number += 1
      book.pages << Page.new(:content => page, :page_number => page_number)
    }
    book.save
    Sunspot.index! book.pages
  rescue Exception => e
    book.index_erro = e.message
    book.save
  end
  
  def self.mybooks(user)
    where(:user_id => user.id)
  end

  def large_image_path
    if cover_img_uuid
      Book.cover_dir + "/cover_#{cover_img_uuid}_large.png"
    else
      "cover_large.png"
    end
  end

  def small_image_path
    if cover_img_uuid
      Book.cover_dir + "/cover_#{cover_img_uuid}_small.png"
    else
      "cover_small.png"
    end
  end

  def thumb_image_path
    if cover_img_uuid
      Book.cover_dir + "/cover_#{cover_img_uuid}_thumb.png"
    else
      "cover_thumb.png"
    end
  end


  def file_full_path
    Rails.root.to_s + "/public" + file.url(:original, :timestamp => false)
  end

  def self.cover_dir
     return "/images/covers"
  end

  def self.full_cover_dir
    return Rails.root.to_s + "/public"+ cover_dir
  end

  def self.recent_books
    return Book.find(:all, :order => "created_at DESC LIMIT 8")
  end

  def self.top_rated_books
    return Book.find(:all, :order => "rating_average DESC LIMIT 12")
  end

  class << self

    def queue
      @queue
    end

    def queue=( new_queue )
      @queue = new_queue
    end

    def deliver(id)
      Resque.enqueue(GenerateBookCover, id)
      Resque.enqueue(Book, id)
    end

    def perform(id)
      new().process(id)
    end

  end
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  respond_to :html, :json

  def index
    @user = current_user
    if(@user.present?)
      @books = Book.mybooks(current_user)
      @shelves = Shelf.where(:user_id => @user.id)
    else
      @books = []
      @shelves = []
    end
    
  end
  
  def search
    
    query    = params[:query]    || ""
    page     = params[:page]     || 1
    per_page = params[:per_page] || 10
    
    busca = Book.search do
      fulltext query do
        highlight :pages_content, :author, :title, :publisher, :fragment_size => 0
      end
      paginate :page => page, :per_page => per_page
    end
    
    

    busca.each_hit_with_result do |hit, result|

      result.author_highlighted        = hit.highlight(:author).format { |word| "<span class='highlight'>#{word}</span>" } rescue ""
      result.title_highlighted         = hit.highlight(:title).format { |word| "<span class='highlight'>#{word}</span>" } rescue ""
      result.publisher_highlighted     = hit.highlight(:publisher).format { |word| "<span class='highlight'>#{word}</span>" } rescue ""
      
      hit.highlights(:pages_content).each{|high|
        result.pages_content_highlighted = high.format { |word| "<span class='highlight'>#{word}</span>" } rescue ""
      }
      
    end

    @books = busca.results
    respond_with @books, :methods => [:author_highlighted, :pages_content_highlighted, :title_highlighted, :publisher_highlighted, :thumb_image_path],
                         :include => [:author]
  end
  
  def new
    @user = current_user
  end
  
  def show
    @user = current_user
    @book = Book.find(params[:id])
    respond_with @book, :include => :author, :methods => [:thumb_image_path]
  end

  def create
    @book = Book.new(params[:book])
    @book.save
    if @book.valid?
      Book.deliver(@book.id)
      render :text => {
        :success => true,
        :book => @book.to_json(:methods => :thumb_image_path)
      }.to_json
    else
      render :text => {
        :success => false,
        :errors => @book.errors
      }.to_json
    end
  end
  
  def update
    @book = Book.find params[:id]
    params[:book].delete :id
    @book.update_attributes(params[:book])    
    respond_with @book
  end
  
  def destroy
    @book = Book.find(params[:id])

    if require_owner(@book)
      Sunspot.remove @book
      @book.destroy
      respond_with @book

    end

  end
  
  private
  def require_owner(book)
    unless current_user.owner_of(book)
      flash[:notice] = "You must be owner to access this page"
      redirect_to home_path
      return false
    end
    return true
  end
  
end

app/views/books/index.html.erb
<div id="sidebar">
  <h2>Insert your books</h2>
  <p>
	  <a href="#new" class="button">Add book</a>
  </p>
  
  <h2>Search your books</h2>
  <p>
	  <a href="#search" class="button">Search Book</a>
  </p>
  
  
  <h2>My Shelves</h2>
  <p>
	  <a href="#create" class="button">Create Shelf</a>
  </p>
  <p id="list_of_shelves">
	  <% @shelves.each{|shelf| %>
	  	<%= link_to shelf.name, "#/shelves/#{shelf.id}" %>
	  <% } %>
  </p>
  
</div>

<ul id="books">
<% @books.each{|book|  %>
	<li class="book_list"><%= link_to image_tag(book.thumb_image_path, :border => 0, :book => book.to_json(:include => :author, :methods => [:thumb_image_path]) ,:title => book.title, :alt => book.title), book %></li>
<% } %>
</ul>

<div id="pagination"></div>

<script type="text/javascript" charset="utf-8" src="/djr"></script>
<%= javascript_include_tag "books/shelves" %>
<%= javascript_include_tag "books/books" %>
<%= javascript_include_tag "books/index" %>

app/views/books/new.html.erb
<div id="add_books"></div>
<script type="text/javascript" charset="utf-8" src="http://cdn.sencha.io/ext-4.0.7-gpl/ext-all.js"></script>

<script>

var current_user = <%= @user.to_json.html_safe %>;

/*

var DJR = function() {
	this.ajax = function(object, callback, error, method, url, params) {};
	for (var action in this.routes) {
      this[action] = function(act) {
          return function(object, callback, error) {
						//..
          }
      }(action);
  }
}

var EmpresaController = function(){
	DJR.call(this);
}; 
EmpresaController.prototype.routes = {};

var EmpresaController = function(){
	this.controller = DJR;
	this.controller();
}; 
EmpresaController.prototype.routes = {};



if(typeof Array.prototype.add == "undefined") {
  Array.prototype.add = function(item) {
      this[this.length] = item;
      return this;
  }
}

Ext.define('Documento', {
	config: { vendedor: ""},
	constructor: function(cfg) {  this.initConfig(cfg);   }
});

Ext.define('PedidoDeVenda', {
	extend: 'Documento',
	incluirVendedor: function(nome) { 
		this.vendedor = nome;
	}
});

Ext.define('NotaFiscal', {
	mixins: {
		pedido: 'PedidoDeVenda'
	},
	extend: 'Documento'
});
var notaFiscal = new NotaFiscal
notaFiscal.incluirVendedor("Milfont");
notaFiscal.getVendedor();

var notaFiscal = new NotaFiscal({valor:200});
var produto = {valor: 50, temEstoque: function() {return true} };
notaFiscal.incluirProduto( produto );

*/

	var Cordel = function(){
		var token, that = this;
		
		that.upload = function(){
        var form = this.up('form').getForm();
        if(form.isValid()){
            form.submit({
                url: '/books',
								params: { 'authenticity_token': token },
                waitMsg: 'Uploading your book...',
                success: function(fp, action) {
									console.log("o", action.result.book);
                }
            });
        }
    };

		that.reset = function() { 
				this.up('form').getForm().reset(); 
		};
		
		that.panel = {
        frame: true,
        bodyPadding: '10 10 0',
        defaults: {  allowBlank: false, msgTarget: 'side', labelWidth: 50,	xtype: 'textfield'},
        items: [
					{xtype: 'hidden', name: 'book[user_id]', value: current_user.id},
					{fieldLabel: 'Title', name: 'book[title]', anchor: '100%'},
					{
					    fieldLabel: 'Author',
					    store: Ext.create('Ext.data.Store', {
							    fields: ['id', 'name'],
									proxy: {
						        type: 'ajax', url : '/authors.json',
						        reader: {
						            type: 'json', root: 'authors'
						        }
									}
							}),
							listeners: {
								validitychange: function( field, isValid, eOpts ){
									fil = field;
									console.log("validitychange", field, isValid, eOpts);
									
								}
							},
							name: 'book[author_id]',
							typeAhead:false, 
							forceSelection:true,
					    queryMode: 'remote',
					    displayField: 'name',
					    valueField: 'id',
					    xtype: 'combo'
					},

					{
	            xtype: 'container',
	            anchor: '100%',
	            layout:'column',
	            items:[{
	                xtype: 'container',
	                columnWidth:.5,
	                layout: 'anchor',
								  defaults: {labelWidth: 50,	xtype: 'textfield'},
	                items: [{anchor: '95%',fieldLabel: 'Publisher', name: 'book[publisher]', allowBlank: true,	xtype: 'textfield'}]
	            },{
	                xtype: 'container',
	                columnWidth:.3,
	                layout: 'anchor',
  								defaults: {labelWidth: 50,	xtype: 'textfield'},
	                items: [{anchor: '90%',fieldLabel: 'Edition', name: 'book[edition]', allowBlank: true,	xtype: 'textfield'}]
	            },{
	                xtype: 'container',
	                columnWidth:.1,
	                layout: 'anchor',
									defaults: {labelWidth: 30,	xtype: 'textfield'},
	                items: [
										{ xtype: 'datefield', fieldLabel: 'Year', name: 'book[year]', allowBlank: true, hideTrigger: true, width: 100, format: 'Y'}
									]
	            }]
	        },
			
//			author
					
					
					{xtype: 'filefield', emptyText: 'Select an book', fieldLabel: 'Book', name: 'book[file]', buttonText: 'choose', anchor: '100%'}
				],
        buttons: [
					{text: 'Save', handler: that.upload},
					{text: 'Reset', handler: that.reset}
				]
    };
		
		return {
			init: function() {
				token = Ext.select("meta[name='csrf-token']").first().getAttribute('content');
				var formPanel = Ext.create('Ext.form.Panel', that.panel);//.render('add_books');
				
				Ext.create('Ext.window.Window', {
				    title: 'Add book to your library',
				    width: 540,
				    layout: 'fit',
				    items: formPanel
				}).show();
				
			}
		}
	}();

	Ext.onReady(function(){
		Cordel.init();
	});
</script>

app/views/books/show.html.erb
<div id="sidebar">
  <% if current_user && current_user.owner_of(@book) %>
    <%= link_to 'Edit', edit_book_path(@book), :class => 'button' %>
    <%= link_to 'Destroy', @book, :confirm => 'Are you sure?', :method => :delete, :class => 'button' %>
  <% end %>
  <p><%= image_tag(@book.small_image_path, :alt => @book.title)%></p>
</div>

<h1><%=h @book.title %></h1>

<p>
  <b>TITLE:</b>
  <%=h @book.title %>
</p>

<p>
  <b>AUTHOR:</b>
  <%=h @book.try(:author).try(:name) %>
</p>

<p>
  <b>YEAR:</b>
  <%=h @book.year %>
</p>

<p>
  <b>EDITION:</b>
  <%=h @book.edition %>
</p>

<p>
  <b>PUBLISHER:</b>
  <%=h @book.publisher %>
</p>

<p>
  <b>PAGES:</b>
  <% if @book.pages.size == 0 %>
  	<span style='color:red;'>waiting for the indexing process finishes!<span/>
  <% else %>
  	<%=h @book.pages.size %> in this file.
  <% end %>
</p>

<% if current_user && current_user.owner_of(@book) %>
<p>
  <b>FILE:</b>
  <a href="<%=h @book.file.url %>">Get book</a>
</p>
<% end %>