config/routes.rb
Cordel::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "sign_in",  :to => "devise/sessions#new"
    get "sign_up",  :to => "devise/registrations#new"
    get "sign_out", :to => "devise/sessions#destroy"  
  end

  devise_scope :user do
    get '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'
    get '/users/auth/facebook/callback' => 'users/omniauth_callbacks#passthru'
  end

  resources :books do
    collection do
      get :search
    end
  end
  
  resources :shelves do
    get :put_the_book_on_the_shelf, :path_prefix => '/shelves/:id', :requirements => { :extra => :book_id }, :on => :member
  end
  
  resources :authors
  
  root :to => "home#index"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cordel</title>
	
	<%= stylesheet_link_tag    "resources/css/ext-all-gray.css" %>
	
	<%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

	<script>
	var current_user = <%= @user.to_json.html_safe %>;
	</script>
	
</head>
<body>

	<div class="miolo">

	<div id="top">
	  <div id="logo">
		  <%= link_to image_tag("logo.gif"), "/" %>
	  </div>
	  <% if current_user %>
	  <div id="user">
		  <div class="user_picture">
	  		<a href="/users/<%= current_user.id %>/edit"><img src="<%= gravatar_url_for current_user.email %>" style="width: 64px; height: 64px" /> </a>
		  </div>
		  <div class="user_infos">
	    	<a href="/users/<%= current_user.id %>/edit"><%= current_user.email %></a>
			<br/>
			<%= link_to "Sign out", sign_out_path %>
		  </div>
	  </div>
	  <% else %>
	  <div id="login">
			<%= link_to "Sign in", sign_in_path %>
			<%= link_to "Sign up", sign_up_path %>
	  </div>
	  <% end %>
	  <ul id="menu">
	    <li><a href="/"<%= "class='active'" if controller.controller_name == 'index' %>>Home</a></li>
	    <li><a href="/books"<%= "class='active'" if controller.controller_name == 'books' %>>My Books</a></li>
	    <% if current_user %>
	      <li><a href="/users/<%= current_user.id %>/edit"<%= "class='active'" if controller.controller_name == 'users' %>>Profile</a></li>
	    <% end %>
	  </ul>
	  <div style="clear: both"></div>
	</div>
	<div id="content">
	  <%= yield %>
	  <div style="clear: both"></div>
	</div>
	<div id="bottom">
	  <b>Cordel</b> is a personal virtual library<br />
	  <span class="white">"Open your mind and go away"</span>
	</div>

	</div>
</body>
</html>